Better exit for test script

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 mkdir -p .tmp
+ecode=0
 
 langs=(c elixir go java javascript php python ruby scala)
 for lang in ${langs[@]}; do
@@ -11,9 +12,11 @@ for lang in ${langs[@]}; do
   total_lines=${parts[0]}
 
   tail -n $(expr $total_lines - $start_line + 1) .tmp/original > .tmp/modified
-  [ $(diff <(tree) .tmp/modified | wc -l) -eq 0 ] &&
-    echo "[pass] $lang" ||
-    echo "[fail] $lang"
+  diffed=$(diff <(tree) .tmp/modified | wc -l)
+
+  [ $diffed -eq 0 ] && echo "[pass] $lang" || echo "[fail] $lang"
+  [ $diffed -ne 0 ] && ecode=1
 done
 
 rm -r .tmp
+exit $ecode
